//报警查询

export const REQUESTERRORLIST = "REQUESTERRORLIST"
export const RECEIVEERRORLIST = "RECEIVEERRORLIST"


//报警导出

export const REQUESTERRORLISTCSV = "REQUESTERRORLISTCSV"
export const RECEIVEERRORLISTCSV = "RECEIVEERRORLISTCSV"


export const REQUESTLENGZHANDATA = "REQUESTLENGZHANDATA"
export const RECEIVELENGZHANDATA = "RECEIVELENGZHANDATA"


export const REQUESTDEVICECOUNT = "REQUESTDEVICECOUNT"
export const RECEIVEDEVICECOUNT = "RECEIVEDEVICECOUNT"


export const REQUESTGETFITTINGS = "REQUESTGETFITTINGS"
export const RECEIVEGETFITTINGS = "RECEIVEGETFITTINGS"

export const REQUESTMAINPLANSET = "REQUESTMAINPLANSET"
export const RECEIVEMAINPLANSET = "RECEIVEMAINPLANSET"

export const REQUESTADDFITTING = "REQUESTADDFITTING"
export const RECEIVEADDFITTING = "RECEIVEADDFITTING"



export const REQUESTMAINPLANSETDETAIL = "REQUESTMAINPLANSETDETAIL"
export const RECEIVEMAINPLANSETDETAIL = "RECEIVEMAINPLANSETDETAIL"





