/**
 * @file actionTypes
 * @author luwenlong <zuiwosuifeng@gmail.com>
 */

// 登录
export const SENDLOGININFO = 'SENDLOGININFO'
export const RECEIVELOGININFO = 'RECEIVELOGININFO'
export const REQUESTLOGINMSGCODE = 'REQUESTLOGINMSGCODE'
export const RECEIVELOGINMSGCODE = 'RECEIVELOGINMSGCODE'

//pc用户名修改
export const REQUESTSETNAME = 'REQUESTSETNAME'
export const RECEIVESETNAME = 'RECEIVESETNAME'
//pc密码修改
export const REQUESTSETPASSWD = 'REQUESTSETPASSWD'
export const RECEIVESETPASSWD = 'RECEIVESETPASSWD'
//pc邮箱修改
export const REQUESTSETMAIL = 'REQUESTSETMAIL'
export const RECEIVESETMAIL = 'RECEIVESETMAIL'
//pc电话修改
export const REQUESTSETPHONE = 'REQUESTSETPHONE'
export const RECEIVESETPHONE = 'RECEIVESETPHONE'

//用户信息
export const REQUESTUSERDETAIL = 'REQUESTUSERDETAIL'
export const RECEIVEUSERDETAIL = 'RECEIVEUSERDETAIL'

//用户列表
export const REQUESTUMANAGELIST = 'REQUESTUMANAGELIST'
export const RECEIVEUMANAGELIST = 'RECEIVEUMANAGELIST'
//新增用户
export const REQUESTUMANAGEADD = 'REQUESTUMANAGEADD'
export const RECEIVEUMANAGEADD = 'RECEIVEUMANAGEADD'
