//时间模板查询

export const REQUESTTIMELIST = "REQUESTTIMELIST"
export const RECEIVETIMELIST = "RECEIVETIMELIST"

//添加时间模板

export const REQUESTADDTIMELIST = "REQUESTADDTIMELIST"
export const RECEIVEADDTIMELIST = "RECEIVEADDTIMELIST"

export const REQUESTMODIFYTIMELIST = "REQUESTMODIFYTIMELIST"
export const RECEIVEMODIFYTIMELIST = "RECEIVEMODIFYTIMELIST"
