//抄表查询

export const REQUESTECHAOBIAOLIST = "REQUESTECHAOBIAOLIST"
export const RECEIVECHAOBIAOLIST = "RECEIVECHAOBIAOLIST"
//获取抄表指标项
export const REQUESTDEVICEINFO = "REQUESTDEVICEINFO"
export const RECEIVEDEVICEINFO = "RECEIVEDEVICEINFO"
//保存抄表数据
export const REQUESTADDCHAOBIAO = "REQUESTADDCHAOBIAO"
export const RECEIVEADDCHAOBIAO = "RECEIVEADDCHAOBIAO"
//查询抄表详细信息
export const REQUESTCHAOBIAOINFO = "REQUESTCHAOBIAOINFO"
export const RECEIVECHAOBIAOINFO = "RECEIVECHAOBIAOINFO"
