//报警查询

export const REQUESTERRORLIST = "REQUESTERRORLIST"
export const RECEIVEERRORLIST = "RECEIVEERRORLIST"


//报警导出

export const REQUESTERRORLISTCSV = "REQUESTERRORLISTCSV"
export const RECEIVEERRORLISTCSV = "RECEIVEERRORLISTCSV"
