//结算单查询
export const REQUESTJIESUANDANLIST = "REQUESTJIESUANDANLIST"
export const RECEIVEJIESUANDANLIST = "RECEIVEJIESUANDANLIST"
//抄表单查询
export const REQUESTECHAOBIAODANLIST = "REQUESTECHAOBIAODANLIST"
export const RECEIVECHAOBIAODANLIST = "RECEIVECHAOBIAODANLIST"
//结算单明细
export const REQUESTJIESUANDANINFO = "REQUESTJIESUANDANINFO"
export const RECEIVEJIESUANDANINFO = "RECEIVEJIESUANDANINFO"
//生成结算单
export const REQUESTADDJIESUANDAN = "REQUESTADDJIESUANDAN"
export const RECEIVEADDJIESUANDAN = "RECEIVEADDJIESUANDAN"
