//查询
export const REQUESTMAPTIMELIST = "REQUESTMAPTIMELIST"
export const RECEIVEMAPTIMELIST = "RECEIVEMAPTIMELIST"

export const REQUESTBENGZHANLIST = "REQUESTBENGZHANLIST"
export const RECEIVEBENGZHANLIST = "RECEIVEBENGZHANLIST"

//时间模板查询
export const REQUESTTIMELIST = "REQUESTTIMELIST"
export const RECEIVETIMELIST = "RECEIVETIMELIST"

//添加巡检计划，Inspection
export const REQUESTINSPECTION = "REQUESTINSPECTION"
export const RECEIVEINSPECTION = "RECEIVEINSPECTION"

//查询指定的时间模板
export const REQUESTTIMEMODEL = "REQUESTTIMEMODEL"
export const RECEIVETIMEMODEL = "RECEIVETIMEMODEL"

//修改巡检计划，Inspection
export const REQUESTINSPECTIONUP = "REQUESTINSPECTIONUP"
export const RECEIVEINSPECTIONUP = "RECEIVEINSPECTIONUP"
