/**
 * @file actionTypes
 * @author luwenlong <zuiwosuifeng@gmail.com>
 */


 export const REQUESTWORKORDERFULL = "REQUESTWORKORDERFULL"
 export const RECEIVEWORKORDERFULL = "RECEIVEWORKORDERFULL"

 export const REQUESTACCEPTWORKORDER = "REQUESTACCEPTWORKORDER"
 export const RECEIVEACCEPTWORKORDER = "RECEIVEACCEPTWORKORDER"

 export const REQUESTCOMPLETEJOB = "REQUESTCOMPLETEJOB"
 export const RECEIVECOMPLETEJOB = "RECEIVECOMPLETEJOB"




 export const REQUESTBAOBIAO = "REQUESTBAOBIAO"
 export const RECEIVEBAOBIAO = "RECEIVEBAOBIAO"

  export const REQUESTYEARMONTH = "REQUESTYEARMONTH"
 export const RECEIVEYEARMONTH = "RECEIVEYEARMONTH"

  export const REQUESTREPORTNOW = "REQUESTREPORTNOW"
 export const RECEIVEREPORTNOW = "RECEIVEREPORTNOW"



 export const REQUESTWORKORDERSTATUS = "REQUESTWORKORDERSTATUS"
 export const RECEIVEWORKORDERSTATUS = "RECEIVEWORKORDERSTATUS"



 export const REQUESTDEVICEASSET = "REQUESTDEVICEASSET"
 export const RECEIVEDEVICEASSET = "RECEIVEDEVICEASSET"

 export const REQUESTCREATEWORKORDER = "REQUESTCREATEWORKORDER"
 export const RECEIVECREATEWORKORDER = "RECEIVECREATEWORKORDER"

 //验收工单
 export const REQUESTREVIEW = "REQUESTREVIEW"
 export const RECEIVEREVIEW = "RECEIVEREVIEW"
