//报警查询

export const REQUESTERRORLIST = "REQUESTERRORLIST"
export const RECEIVEERRORLIST = "RECEIVEERRORLIST"


//报警导出

export const REQUESTERRORLISTCSV = "REQUESTERRORLISTCSV"
export const RECEIVEERRORLISTCSV = "RECEIVEERRORLISTCSV"



export const REQUESTLENGZHANDATA = "REQUESTLENGZHANDATA"
export const RECEIVELENGZHANDATA = "RECEIVELENGZHANDATA"


export const REQUESTMAINPLANSET = "REQUESTMAINPLANSET"
export const RECEIVEMAINPLANSET = "RECEIVEMAINPLANSET"
 
export const REQUESTMAINPLANSETDETAIL = "REQUESTMAINPLANSETDETAIL"
export const RECEIVEMAINPLANSETDETAIL = "RECEIVEMAINPLANSETDETAIL"

export const REQUESTTOTALFITTING = "REQUESTTOTALFITTING"
export const RECEIVETOTALFITTING = "RECEIVETOTALFITTING"


export const REQUESTADDREPAIR = "REQUESTADDREPAIR"
export const RECEIVEADDREPAIR = "RECEIVEADDREPAIR"

