//报警查询

export const REQUESTERRORLIST = "REQUESTERRORLIST"
export const RECEIVEERRORLIST = "RECEIVEERRORLIST"


//报警导出

export const REQUESTERRORLISTCSV = "REQUESTERRORLISTCSV"
export const RECEIVEERRORLISTCSV = "RECEIVEERRORLISTCSV"


export const REQUESTDEVICECOUNT = "REQUESTDEVICECOUNT"
export const RECEIVEDEVICECOUNT = "RECEIVEDEVICECOUNT"


export const REQUESTLENGZHANDATA = "REQUESTLENGZHANDATA"
export const RECEIVELENGZHANDATA = "RECEIVELENGZHANDATA"


export const REQUESTDEVICEBYTYPE = "REQUESTDEVICEBYTYPE"
export const RECEIVEDEVICEBYTYPE = "RECEIVEDEVICEBYTYPE"

export const REQUESTADDDEVICE = "REQUESTADDDEVICE"
export const RECEIVEADDDEVICE = "RECEIVEADDDEVICE"



export const REQUESTDEVICEINFO = "REQUESTDEVICEINFO"
export const RECEIVEDEVICEINFO = "RECEIVEDEVICEINFO"





