//报警查询

export const REQUESTERRORLIST = "REQUESTERRORLIST"
export const RECEIVEERRORLIST = "RECEIVEERRORLIST"


//报警导出

export const REQUESTERRORLISTCSV = "REQUESTERRORLISTCSV"
export const RECEIVEERRORLISTCSV = "RECEIVEERRORLISTCSV"

export const REQUESTABNORMAL = "REQUESTABNORMAL"
export const RECEIVEABNORMAL = "RECEIVEABNORMAL"


export const REQUESTCREATEABNORMAL = "REQUESTCREATEABNORMAL"
export const RECEIVECREATEABNORMAL = "RECEIVECREATEABNORMAL"

 export const REQUESTWORKORDERSTATUS = "REQUESTWORKORDERSTATUS"
 export const RECEIVEWORKORDERSTATUS = "RECEIVEWORKORDERSTATUS"


 export const REQUESTABNORMALFULL = "REQUESTABNORMALFULL"
export const RECEIVEABNORMALFULL = "RECEIVEABNORMALFULL"
