/**
 * @file actionTypes
 * @author luwenlong <zuiwosuifeng@gmail.com>
 */
//根据topic查询对应的设备
 export const REQUESTXIAOXIBAOXIU = "REQUESTXIAOXIBAOXIU"
 export const RECEIVEXIAOXIBAOXIU = "RECEIVEXIAOXIBAOXIU"
 //查询报修详细信息
export const REQUESTXIAOXIBAOXIUXQ = 'REQUESTXIAOXIBAOXIUXQ'
export const RECEIVEXIAOXIBAOXIUXQ = 'RECEIVEXIAOXIBAOXIUXQ'
//维护详情
export const REQUESTXIAOXIWEIHUXQ = 'REQUESTXIAOXIWEIHUXQ'
export const RECEIVEXIAOXIWEIHUXQ = 'RECEIVEXIAOXIWEIHUXQ'
//巡检模板
export const REQUESTXJMB = 'REQUESTXJMB'
export const RECEIVEXJMB = 'RECEIVEXJMB'

//巡检展示show
export const REQUESTXJSHOW = 'REQUESTXJSHOW'
export const RECEIVEXJSHOW = 'RECEIVEXJSHOW'

//清空未读消息数
export const REQUESTCLEARUNREAD = 'REQUESTCLEARUNREAD'
export const RECEIVECLEARUNREAD = 'RECEIVECLEARUNREAD'

   
