//巡检计划查询

export const REQUESTXUNJIANLIST = "REQUESTXUNJIANLIST"
export const RECEIVEXUNJIANLIST = "RECEIVEXUNJIANLIST"
//巡检单查询
export const REQUESTXUNJIANDAN = "REQUESTXUNJIANDAN"
export const RECEIVEXUNJIANDAN = "RECEIVEXUNJIANDAN"
