/**
 * @file actionTypes
 * @author luwenlong <zuiwosuifeng@gmail.com>
 */


 //获取冷站监测SVG的数据
  export const REQUESTLENGZHANDATA='REQUESTLENGZHANDATA'
  export const RECEIVELENGZHANDATA='RECEIVELENGZHANDATA'
 //获取冷站功率及COP数据
  export const REQUESTPOWERDATA='REQUESTPOWERDATA'
  export const RECEIVEPOWERDATA='RECEIVEPOWERDATA'
 //获取能耗数据图表
  export const REQUESTENERGYDATA='REQUESTENERGYDATA'
  export const RECEIVEENERGYDATA='RECEIVEENERGYDATA'

  //获取末端数据
   export const REQUESTTERMDATA='REQUESTTERMDATA'
   export const RECEIVETERMDATA='RECEIVETERMDATA'


    //获取实时数据
    export const REQUESTREAL='REQUESTREAL_MONITOR'
    export const RECEIVEREAL='RECEIVEREAL_MONITOR'


    //获取小时历史数据
    export const REQUESTHISHOUR='REQUESTHISHOUR_MONITOR'
    export const RECEIVEHISHOUR='RECEIVEHISHOUR_MONITOR'

    //获取日历史数据
    export const REQUESTHISDAY='REQUESTHISDAY_MONITOR'
    export const RECEIVEHISDAY='RECEIVEHISDAY_MONITOR'


    //获取月历史数据
    export const REQUESTHISMONTH='REQUESTHISMONTH_MONITOR'
    export const RECEIVEHISMONTH='RECEIVEHISMONTH_MONITOR'
    //获取年历史数据
    export const REQUESTHISYEAR='RECEIVEHISYEAR_MONITOR'
    export const RECEIVEHISYEAR='RECEIVEHISYEAR_MONITOR'
    //获取时间段内所有数据
    export const REQUESTHISWHOLE='REQUESTHISWHOLE_MONITOR'
    export const RECEIVEHISWHOLE='REQUESTHISWHOLE_MONITOR'




    //获取小时报表数据
    export const REQUESTREPHOUR='REQUESTREPHOUR_MONITOR'
    export const RECEIVEREPHOUR='RECEIVEREPHOUR_MONITOR'

    //获取日报表数据
    export const REQUESTREPDAY='REQUESTREPDAY_MONITOR'
    export const RECEIVEREPDAY='RECEIVEREPDAY_MONITOR'

    //获取周报表数据
    export const REQUESTREPWEEK='REQUESTREPWEEK_MONITOR'
    export const RECEIVEREPWEEK='RECEIVEREPWEEK_MONITOR'

    //获取月报表数据
    export const REQUESTREPMONTH='REQUESTREPMONTH_MONITOR'
    export const RECEIVEREPMONTH='RECEIVEREPMONTH_MONITOR'
    //获取年报表数据
    export const REQUESTREPYEAR='RECEIVEREPYEAR_MONITOR'
    export const RECEIVEREPYEAR='RECEIVEREPYEAR_MONITOR'
