/**
 * @file actionTypes
 * @author zlc <lichao9182@126.com>
 */

 export const REQUESTBAOBIAO = "REQUESTBAOBIAO"
 export const RECEIVEBAOBIAO = "RECEIVEBAOBIAO"

  export const REQUESTYEARMONTH = "REQUESTYEARMONTH"
 export const RECEIVEYEARMONTH = "RECEIVEYEARMONTH"

  export const REQUESTREPORTNOW = "REQUESTREPORTNOW"
 export const RECEIVEREPORTNOW = "RECEIVEREPORTNOW"
