//抄表单查询
export const REQUESTECHAOBIAODANLIST = "REQUESTECHAOBIAODANLIST"
export const RECEIVECHAOBIAODANLIST = "RECEIVECHAOBIAODANLIST"
//抄表查询
export const REQUESTECHAOBIAOLIST = "REQUESTECHAOBIAOLIST"
export const RECEIVECHAOBIAOLIST = "RECEIVECHAOBIAOLIST"
//抄表单明细
export const REQUESTCHAOBIAODANINFO = "REQUESTCHAOBIAODANINFO"
export const RECEIVECHAOBIAODANINFO = "RECEIVECHAOBIAODANINFO"
//生成抄表单
export const REQUESTADDCHAOBIAODAN = "REQUESTADDCHAOBIAODAN"
export const RECEIVEADDCHAOBIAODAN = "RECEIVEADDCHAOBIAODAN"
